server:
  port: 8888


spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/feng?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root
    slave:
      jdbc-url: jdbc:mysql://localhost:3307/feng2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: root